### ISSUE TITLE
Créer un simulateur de l'interface physique qui envoie les mêmes messages que l'interface physique

### ISSUE THREAD

**Issue by thomasfredericks** [Sonalux-projet2024/Sonalux#11]

**Comment by vince1887** [comment]
![interieur_interface_virtuel](https://github.com/Sonalux2024/Sonalux/assets/93718079/e1110185-408e-45f0-9cb1-50c23d258d14)
![interface_virtuel-osc-in](https://github.com/Sonalux2024/Sonalux/assets/93718079/e2ce4684-a839-404c-9e49-a477277a96e0)
![interieur_composant_osc](https://github.com/Sonalux2024/Sonalux/assets/93718079/1ec6f31c-445d-4601-83ee-c33dda9b6210)

**Comment by vince1887** [comment]
![interface_virtuel](https://github.com/Sonalux2024/Sonalux/assets/93718079/890c41df-df24-4de5-a3e4-2af41f950dc3)
