### ISSUE TITLE
Créer un méta-patcher TouchDesigner qui charge les différentes scènes

### ISSUE THREAD

**Issue by thomasfredericks** [Sonalux-projet2024/Sonalux#12]

**Comment by vince1887** [comment]
![meta_patcher](https://github.com/Sonalux2024/Sonalux/assets/93718079/3bd7b401-e131-448b-b0f9-d90f8c4f12aa)
la zone rouge: On retrouve les 3 chapitre en mode composante(.tox) ainsi qu'un TOP switch pour faire le changement de scène  entre les 3 chapitres
la zone bleu: Nn composant temporaire qui faire le changement de scène a tout les 300 frames sur la timeline
la zone noir en haut a gauche: le module qui traite les donne osc. Ensuite chaque composant de génération visuel reçoit le même ensemble de donné
